DATA_CLEAN_SUBJECT = 'data/clean-mails-data.csv'
DATA_CLEAN_SUBJECT_INF = 'data/clean-mails-data-inf.csv'
DATA_CLEAN_EMPTY_SUBJECT = 'data/clean-empty-subject-mails-data.csv'

DATA_CLEAN_SUBJECT_TIME = 'data/clean-time-mails-data.csv'
DATA_CLEAN_EMPTY_SUBJECT_TIME = 'data/clean-empty-subject-time-mails-data.csv'

SUBJECT_GROUPS = 'data/subject-groups/groups.json'
ALPHABETICAL_SUBJECT_GROUPS = 'data/subject-groups/alphabetical_groups.json'

SUBJECT_GROUPS_1 = 'data/subject-groups/groups_1.json'
SUBJECT_GROUPS_2 = 'data/subject-groups/groups_2.json'
SUBJECT_GROUPS_2_PLUS = 'data/subject-groups/groups_2_plus.json'
SUBJECT_GROUPS_3 = 'data/subject-groups/groups_3.json'
SUBJECT_GROUPS_3_PLUS = 'data/subject-groups/groups_3_plus.json'
SUBJECT_GROUPS_6 = 'data/subject-groups/groups_6.json'

SUBJECT_GROUPS_2_TIME = 'data/subject-groups/groups_2_time.json'
SUBJECT_GROUPS_2_PLUS_TIME = 'data/subject-groups/groups_2_plus_time.json'
SUBJECT_GROUPS_3_TIME = 'data/subject-groups/groups_3_time.json'
SUBJECT_GROUPS_3_PLUS_TIME = 'data/subject-groups/groups_3_plus_time.json'
SUBJECT_GROUPS_6_TIME = 'data/subject-groups/groups_6_time.json'

CHECK_CHAINS = 'data/check-chains/'

ORDERED_GROUPS = 'data/chains/ordered_groups.json'
CHAINS = 'data/chains/chains.json'

CHAINS_1 = 'data/chains/chains_1.json'
CHAINS_1_NEW = 'data/chains/chains_1_new.json'
CHAINS_2 = 'data/chains/chains_2.json'
CHAINS_2_NEW = 'data/chains/chains_2_new.json'
CHAINS_3 = 'data/chains/chains_3.json'
CHAINS_4 = 'data/chains/chains_4.json'
CHAINS_5 = 'data/chains/chains_5.json'
CHAINS_6 = 'data/chains/chains_6.json'
CHAINS_7 = 'data/chains/chains_7.json'
CHAINS_8 = 'data/chains/chains_8.json'
CHAINS_9 = 'data/chains/chains_9.json'
CHAINS_10 = 'data/chains/chains_10.json'
CHAINS_10_PLUS = 'data/chains/chains_10_plus.json'